markdown: kramdown
theme: minima
title: Metagov Journal
description: A journal for institutional experiments

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Set to `true` to show excerpts on the homepage.
header_pages:
  - submit.md

show_excerpts: true

google_analytics: 

# see https://github.com/jekyll/minima/blob/master/_config.yml for examples
