theme: minima
title: Metagov Journal
description: A journal for institutional experiments

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
header_pages:
  - about.md
  - submit.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# see https://github.com/jekyll/minima/blob/master/_config.yml for examples
