markdown: kramdown
theme: minima
title: Metagov Journal
description: A journal for institutions
author:
  name: Metagov, Inc.
  email: hello@metagov.org

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

google_analytics: G-8CM1DYG2FB

# see https://github.com/jekyll/minima/blob/master/_config.yml for examples
